Fix: improper page attributes and parameters
appwrite/docs pull request #107
Opened 2021-10-30 18:25 UTC by michizhou

Fixed inconsistent heading reference attributes for Functions and Rules documentation pages and misspelled PHP attributes in Index and Service page scripts. Also fixed typo on word "Appwrite" in Functions documentation page.

2021-11-02 17:42 UTC, michizhou commented
@Meldiron @eldadfux Please feel free to look over this PR whenever you are available to do so.

2021-11-06 11:46 UTC, eldadfux requested changes

2021-11-06 11:46 UTC, eldadfux commented on app/views/docs/index.phtml
> +<div class="zone <?php echo $layout; ?> docs" data-general-stretch-value="<?php echo $layout; ?>">
```suggestion
<div class="zone <?php echo $layout; ?> docs" data-general-strech-value="<?php echo $layout; ?>">
```

We should keep the typo here until this is also fixed in appwrite/appwrite css files and other templates.

2021-11-08 11:49 UTC, merged

2021-11-08 11:49 UTC, eldadfux commented
Thanks for contributing @michizhou! Let me know on Discord if you haven't claimed your Appwrite Swags yet