Add error codes
appwrite/docs pull request #139
Opened 2022-02-06 23:07 UTC by christyjacob4

2022-02-07 06:16 UTC, eldadfux requested changes
What should we do with the 1st table in the page? I feel the difference between them is not very clear for the reader.

2022-02-07 06:16 UTC, eldadfux commented on app/views/docs/error-codes.phtml
> +<h2><a href="/docs/functions#environmentVariables" id="environmentVariables">Error Codes</a></h2>
```suggestion
<h2><a href="/docs/functions#environmentVariables" id="environmentVariables">Error Codes</a></h2>
```

The link and ID are wrong.

2022-02-07 06:16 UTC, eldadfux commented on app/views/docs/error-codes.phtml
>      "code": 400
We should update the code example.

2022-02-07 22:41 UTC, christyjacob4 commented on app/views/docs/error-codes.phtml
>      "code": 400
done 👍

2022-02-07 23:26 UTC, christyjacob4 commented on app/views/docs/error-codes.phtml
> +<h2><a href="/docs/functions#environmentVariables" id="environmentVariables">Error Codes</a></h2>
fixed

2022-02-07 23:28 UTC, christyjacob4 commented
@eldadfux  the first table talks about the convention we follow when deciding an HTTP status code for our errors. And the second table talks more about Appwrite specific error codes.

2022-02-08 05:48 UTC, eldadfux approved these changes

2022-02-08 05:49 UTC, eldadfux commented
I would only consider adding the version we started supporting each error code. We have something similar for env vars.

2022-02-08 15:43 UTC, christyjacob4 commented
@eldadfux In this case, I'm not sure we can follow the convention we use for ENV Vars.
![Screenshot 2022-02-08 at 7 41 46 PM](https://user-images.githubusercontent.com/20852629/153022058-9467f536-4e71-4c99-8b1d-cb0f063516b6.png)
 
Since we introduced all these error codes in 0.13. literally every row in the table will have this information and it'll just make the table very noisy. 

It's probably a better option to mention that this feature was introduced in `0.13` once in one of the paragraphs above. 

From 0.14 onwards, we can start following the ENV Vars convention

2022-02-08 16:38 UTC, christyjacob4 commented
![Screenshot 2022-02-08 at 8 37 24 PM](https://user-images.githubusercontent.com/20852629/153032945-7d5bd812-1d74-49f4-a29f-5bfb24e8eee8.png)


@eldadfux  updated the description to add the note

2022-02-08 20:46 UTC, gewenyu99 approved these changes
LGTM <3

2022-02-08 22:50 UTC, christyjacob4 commented
## Latest Preview

![Screenshot 2022-02-09 at 2 49 56 AM](https://user-images.githubusercontent.com/20852629/153088867-87899850-87cc-4366-828f-60e0a3b231cc.png)

2022-02-09 10:55 UTC, Meldiron approved these changes
LGTM

2022-02-14 06:22 UTC, eldadfux commented
Changed target branch to 0.13

2022-02-16 23:15 UTC, merged