Feat functions docs improvements
appwrite/docs pull request #144
Opened 2022-02-20 12:57 UTC by christyjacob4

2022-02-20 14:26 UTC, eldadfux commented
The indentation in some of the code examples is wrong.

2022-02-20 14:37 UTC, eldadfux commented
Maybe we can also use a friendlier examples with some usage of headers or env vars.

2022-02-20 14:43 UTC, eldadfux commented
On the execute section, it would be nice to get iOS and Android examples.

2022-02-20 15:04 UTC, eldadfux requested changes

2022-02-20 15:04 UTC, eldadfux commented on app/views/docs/functions.phtml
> +    <h3>A note about build times</h3>
```suggestion
    <h3>Build Times</h3>
```

2022-02-20 16:55 UTC, christyjacob4 commented
> The indentation in some of the code examples is wrong.

Fixed 👍 

> Maybe we can also use a friendlier examples with some usage of headers or env vars.

For all the runtimes ? Or some specific ones only ?  @eldadfux 

> On the execute section, it would be nice to get iOS and Android examples.

Done 👍

2022-02-22 10:32 UTC, christyjacob4 commented
Please don't merge it yet. The example code for ruby and swift is still under works

2022-02-22 23:09 UTC, eldadfux approved these changes

2022-02-23 16:51 UTC, christyjacob4 commented
![screencapture-localhost-2080-docs-functions-2022-02-23-20_51_02](https://user-images.githubusercontent.com/20852629/155367034-3dfab94b-95a3-470e-b401-ff6e465f7915.png)
Latest Screenshot

2022-02-24 11:41 UTC, merged