Explain how to use Appwrite SDKs in Appwrite Functions
appwrite/docs pull request #184
Opened 2022-05-09 21:21 UTC by gewenyu99

A frequently asked question since 0.13 is how to use Appwrite SDKs in Appwrite Functions. This is frequently pointed out as missing in the documentation.

Furthermore, it's especially apparent that many (including myself) did not know endpoint and API keys needed to be passed in manually as variables in Appwrite Functions. This was noticed on Discord over launch and during the Hackathon.

This PR adds a snippet pointing to code examples and points out which variables must be added.

2022-05-11 21:06 UTC, gewenyu99 commented
<img width="912" alt="Screen Shot 2022-05-11 at 5 05 05 PM" src="https://user-images.githubusercontent.com/29069505/167947603-6f884fe9-79aa-4565-affb-dcbeb1f9cf5e.png">

Preview for the proposed change.

2022-05-12 16:30 UTC, TorstenDittmann requested changes

2022-05-12 16:30 UTC, TorstenDittmann commented on app/views/docs/functions.phtml
> +<p>To initialize a Server SDK in a function, you need to provide your Appwrite project's endpoint and an <a href="https://appwrite.io/docs/keys" target="_blank">API key</a> as variables in the <b>Set
```suggestion
<p>You can integrate Appwrite Functions with other Appwrite services by using the appropriate <a href="/docs/getting-started-for-server" target="_blank">Server SDK</a> for your runtime. You can find starter code for your function's runtime in the <a href="https://github.com/appwrite/functions-starter" target="_blank">Appwrite Function Starter repository</a>.</p>

<p>To initialize a Server SDK in a function, you need to provide your Appwrite project's endpoint and an <a href="/docs/keys" target="_blank">API key</a> as variables in the <b>Settings</b> tab of your Function. The ID of your Appwrite project is passed in automatically as <span class="tag">APPWRITE_FUNCTION_PROJECT_ID</span>.</p>
```

2022-05-12 17:41 UTC, TorstenDittmann approved these changes

2022-05-12 17:41 UTC, merged