Add C++ function example to Functions guide
appwrite/docs pull request #200
Opened 2022-06-13 12:59 UTC by adityaoberai

2022-06-13 16:53 UTC, adityaoberai commented
@Meldiron I had a chat with @christyjacob4 and until Prism syntax highlighting for C++ is fixed, I've added C# highlighting as a temporary fix.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/31401437/173404927-2b6ecc81-fe0f-47f6-bc54-a0303196dc4d.png">

2022-06-13 20:56 UTC, christyjacob4 commented on app/views/docs/functions.phtml
> +    std::string payload = req.payload.empty() ?
```suggestion
    string payload = req.payload.empty() ? 
```

You can replace all the `std::` by writing `using namespace std;` at the top of the file after all the imports. Can you try it once and test out the code ?

2022-06-13 20:56 UTC, christyjacob4 requested changes
Just one comment, if we can try to simplify the example it would be awesome! 🙂

2022-06-14 04:54 UTC, adityaoberai commented on app/views/docs/functions.phtml
> +    std::string payload = req.payload.empty() ?
@christyjacob4  I tried it out and does not work. Got following error when deploying the function:

```bash
Docker Error: rm: can't remove 'CMakeCache.txt': No such file or directory
In file included from /usr/local/src/src/main.cc:4:
/usr/local/src/src/Wrapper.h:14:7: error: expected nested-name-specifier before 'namespace'
    | using namespace std;
      |       ^~~~~~~~~
make[]: *** [CMakeFiles/cpp_runtime.dir/build.make:76: CMakeFiles/cpp_runtime.dir/src/main.cc.o] Error 
make[]: *** [CMakeFiles/Makefile2:83: CMakeFiles/cpp_runtime.dir/all] Error 
make: *** [Makefile:91: all] Error 
-- The CXX compiler identification is GNU .1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include any
-- Looking for C++ include any - found
-- Looking for C++ include string_view
-- Looking for C++ include string_view - found
-- Looking for C++ include coroutine
-- Looking for C++ include coroutine - not found
-- Found Jsoncpp: /usr/include  
-- jsoncpp verson:1.9.5
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1o")  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found UUID: /usr/lib/libuuid.so
-- Found ZLIB: /lib/libz.so (found version "1.2.12") 
-- Found Brotli: /usr/lib/libbrotlidec.so  
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - found
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED - Success
-- use c++17
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/build
[ %] Building CXX object CMakeFiles/cpp_runtime.dir/src/main.cc.o
```

As per some reviewing on Stack Overflow, it might have to do with our [GCC version](https://stackoverflow.com/questions/21036062/compiler-error-expected-nested-name-specifier).

Further reading also showed that it might actually be a [bad practice](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice) to write `using namespace std;` there.

Not sure how to move forward here, would love to know what you recommend. Personally, I think we should keep this working example until we can figure out how to mitigate this error in the runtime.

2022-06-14 13:55 UTC, christyjacob4 approved these changes

2022-06-14 14:08 UTC, merged