Feat: Add query docs
appwrite/docs pull request #205
Opened 2022-06-24 19:23 UTC by gewenyu99

This file adds docs for the query class. This serves to display all available options, so users don't need to guess what query methods are available. This is a prerequisite for adding a more detailed explanation for the search parameter in various endpoints.

2022-06-24 19:47 UTC, gewenyu99 commented
Supported by this PR to homepage: https://github.com/appwrite/homepage/pull/47

2022-06-24 19:49 UTC, gewenyu99 commented
<img width="555" alt="Screen Shot 2022-06-24 at 3 48 58 PM" src="https://user-images.githubusercontent.com/29069505/175657638-11679273-8fa1-4f07-895d-6ed0be979a13.png">

2022-06-27 09:45 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +        <div class="ide" data-lang="javascript" data-lang-label="Flutter SDK">
```suggestion
        <div class="ide" data-lang="dart" data-lang-label="Flutter SDK">
```

2022-06-27 09:45 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +String queryString = Query.equal(attribute, value);
Is Query automatically imported when importing the Appwrite package? In the web SDK, we need to import it separately.

2022-06-27 09:46 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +print(queryString)</code></pre>
This is the dart example, let's update it to use the Kotlin example

2022-06-27 09:50 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +console.log(queryString);</code></pre>
I see that we're printing the query string in each case, it seems unnecessary unless we show what the output looks like ... 

I think we can use two approaches here 

```js
import { Query } from "appwrite";

let attribute = "name";
let value = "Avengers";

const queryString = Query.equal(attribute, value);
console.log(queryString); // name=Avengers 
```

2022-06-27 09:53 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +console.log(queryString);</code></pre>
In all these examples , we should mention that `value` can either be a single value like `Avengers` or a list of values like `['Avengers', 'Titanic']`

2022-06-27 09:54 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +console.log(queryString);</code></pre>
Reference : https://github.com/appwrite/sdk-for-web/blob/master/src/sdk.ts#L3748-L3767

2022-06-27 09:55 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +let queryString = Query.equal(attribute, value)
Please check if the query class is imported as part of the Appwrite package or needs an explicit import

2022-06-27 09:56 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +Returns results where the specified <b>attribute</b> is exactly equal to <b>value</b>.
In all these examples , we should mention that value can either be a single value like `Avengers` or a list of values like `['Avengers', 'Titanic', 'Iron Man']`

Reference : https://github.com/appwrite/sdk-for-web/blob/master/src/sdk.ts#L3748-L3767

2022-06-27 09:57 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +Returns results where the specified <b>attribute</b> is not equal to <b>value</b>.
In all these examples , we should mention that value can either be a single value like `Avengers` or a list of values like `['Avengers', 'Titanic', 'Iron Man']`

Reference : https://github.com/appwrite/sdk-for-web/blob/master/src/sdk.ts#L3748-L3767

2022-06-27 09:57 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +        <div class="ide" data-lang="javascript" data-lang-label="Flutter SDK">
```suggestion
        <div class="ide" data-lang="dart" data-lang-label="Flutter SDK">
```

2022-06-27 09:58 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +            <pre class="line-numbers"><code class="prism language-kotlin" data-prism>import 'package:appwrite/appwrite.dart';
Replace with the Kotlin import

2022-06-27 09:58 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +Returns results where the specified <b>attribute</b> is less than <b>value</b>. Can be applied to strings where comparison is based on alphabetical order.
In all these examples , we should mention that value can either be a single value like `Avengers` or a list of values like `['Avengers', 'Titanic', 'Iron Man']`

Reference : https://github.com/appwrite/sdk-for-web/blob/master/src/sdk.ts#L3748-L3767

2022-06-27 09:59 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +        <div class="ide" data-lang="javascript" data-lang-label="Flutter SDK">
```suggestion
        <div class="ide" data-lang="dart" data-lang-label="Flutter SDK">
```

2022-06-27 09:59 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +            <pre class="line-numbers"><code class="prism language-kotlin" data-prism>import 'package:appwrite/appwrite.dart';
Reminder to use the Kotlin import

2022-06-27 09:59 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +Returns results where the specified <b>attribute</b> is less than or equal to <b>value</b>. Can be applied to strings where comparison is based on alphabetical order.
In all these examples , we should mention that value can either be a single value like `Avengers` or a list of values like `['Avengers', 'Titanic', 'Iron Man']`

Reference : https://github.com/appwrite/sdk-for-web/blob/master/src/sdk.ts#L3748-L3767

2022-06-27 10:02 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +Returns results where the specified <b>attribute</b> is not equal to <b>value</b>.
You can use a numerical example to make it more clear

2022-06-27 10:02 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +Returns results where the specified <b>attribute</b> is less than <b>value</b>. Can be applied to strings where comparison is based on alphabetical order.
You can use a numerical example to make it more clear

2022-06-27 10:02 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +Returns results where the specified <b>attribute</b> is less than or equal to <b>value</b>. Can be applied to strings where comparison is based on alphabetical order.
You can use a numerical example to make it more clear

2022-06-27 10:03 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +        <div class="ide" data-lang="javascript" data-lang-label="Flutter SDK">
```suggestion
        <div class="ide" data-lang="dart" data-lang-label="Flutter SDK">
```

2022-06-27 10:03 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +Returns results where the specified <b>attribute</b> is greater than <b>value</b>. Can be applied to strings where comparison is based on alphabetical order.
In all these examples , we should mention that value can either be a single value like Avengers or a list of values like ['Avengers', 'Titanic', 'Iron Man']

Reference : https://github.com/appwrite/sdk-for-web/blob/master/src/sdk.ts#L3748-L3767

You can use a numerical example to make it more clear

2022-06-27 10:04 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +        <div class="ide" data-lang="javascript" data-lang-label="Flutter SDK">
```suggestion
        <div class="ide" data-lang="dart" data-lang-label="Flutter SDK">
```

2022-06-27 10:04 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +String queryString = Query.greaterEqual(attribute, value);
```suggestion
String queryString = Query. greater(attribute, value);
```

2022-06-27 10:04 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +            <pre class="line-numbers"><code class="prism language-kotlin" data-prism>import 'package:appwrite/appwrite.dart';
Reminder to use the Kotlin import

2022-06-27 10:04 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +String queryString = Query.greaterEqual(attribute, value)
```suggestion
String queryString = Query. greater(attribute, value)
```

2022-06-27 10:05 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +Returns results where the specified <b>attribute</b> is greater than or equal to <b>value</b>. Can be applied to strings where comparison is based on alphabetical order.
In all these examples , we should mention that value can either be a single value like Avengers or a list of values like ['Avengers', 'Titanic', 'Iron Man']

Reference : https://github.com/appwrite/sdk-for-web/blob/master/src/sdk.ts#L3748-L3767

You can use a numerical example to make it more clear

2022-06-27 10:06 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +        <div class="ide" data-lang="javascript" data-lang-label="Flutter SDK">
```suggestion
        <div class="ide" data-lang="dart" data-lang-label="Flutter SDK">
```

2022-06-27 10:06 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +        <div class="ide" data-lang="javascript" data-lang-label="Flutter SDK">
```suggestion
        <div class="ide" data-lang="dart" data-lang-label="Flutter SDK">
```

2022-06-27 10:06 UTC, christyjacob4 commented on app/views/docs/query.phtml
> +            <pre class="line-numbers"><code class="prism language-kotlin" data-prism>import 'package:appwrite/appwrite.dart';
Reminder to use the Kotlin import

2022-06-27 10:07 UTC, christyjacob4 requested changes
Please address the comments

2023-01-24 20:51 UTC, closed without merging