Add new response codes from 0.16
appwrite/docs pull request #237
Opened 2022-08-17 01:11 UTC by gewenyu99

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2022-08-19 21:32 UTC, gewenyu99 commented
<img width="1003" alt="Screen Shot 2022-08-19 at 5 31 29 PM" src="https://user-images.githubusercontent.com/29069505/185710026-1eb28c1c-ec5f-4c18-9087-78ffad1fb921.png">
<img width="1003" alt="Screen Shot 2022-08-19 at 5 31 51 PM" src="https://user-images.githubusercontent.com/29069505/185710027-c7eba33d-88bf-48c8-923d-f9262bba5737.png">

2022-08-20 03:29 UTC, eldadfux reviewed
We need to make sure we update the appwrite/homepage, appwrite/appwrite and appwrite/docs with the new link.

2022-08-22 10:14 UTC, christyjacob4 commented on app/views/docs/index.phtml
> +                    <li><a href="/docs/response-codes">Response Codes</a></li>
reminder to update this file as well
https://github.com/appwrite/homepage/blob/cc7e8ddcbc3bf401e16e34cf8f46a2d97b65400c/app/controllers/home.php#L538-L541

2022-08-22 10:15 UTC, christyjacob4 requested changes
Some small comments

2022-08-23 02:48 UTC, merged