0.16.x
appwrite/docs pull request #238
Opened 2022-08-23 03:20 UTC by christyjacob4

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2022-09-03 01:37 UTC, abnegate requested changes

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +    <p>You will need an active session to perform create, update, and delete type actions in your collections. Even if create, update, and delete permissions are granted to "Role.any()", you still ne
> You will need an active session to perform create, update, and delete type actions in your collections

This is no longer true

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +<p>A server or <a href="/docs/admin">admin integration</a> can be used for increased flexibility. When using a Server SDK in combination with the proper <a href="/docs/keys#scopes">API key scopes</a>
```suggestion
<p>A server or <a href="/docs/admin">admin integration</a> can be used for increased flexibility. When using a Server SDK in combination with the proper <a href="/docs/keys#scopes">API key scopes</a>, you can have any type of access to any of your project resources regardless of their permissions.</p>
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +<h2 id="permission-types"><a href="/docs/permissions#permission-types">Permission Types</a></h2>
I think this block should come before `Permission Roles`

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +        <td>Access to view a resource. Does not apply to functions.</td>
> Does not apply to functions.

I think we can remove all instances of this as functions won't use permissions, only roles

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +        <td>Access to view a resource. Does not apply to functions.</td>
```suggestion
        <td>Access to read a resource.</td>
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +        <td>Alias to grant all of create, update, and delete access.</td>
> create, update, and delete access.

Will only grant update, delete for documents and files

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +<p>In the following example, we are creating a document that can be viewed by anyone, edited by writers or admins, and deleted by a user with the user ID <span class="tag">user:5c1f88b42259e</span> o
```suggestion
<p>In the following example, we are creating a document that can be read by anyone, edited by writers or admins, and deleted by administrators or a user with the user ID <span class="tag">user:5c1f88b42259e</span>.</p>
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +<p>In the following example, we are creating a document that can be read-only by members of the team with ID <span class="tag">5c1f88b87435e</span> and can only be edited or deleted by members of the
```suggestion
<p>In the following example, we are creating a document that can be read by members of the team with ID <span class="tag">5c1f88b87435e</span> and can only be edited or deleted by members of the same team that possess the team role <span class="tag">owner</span>.</p>
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +        Permission.edit([Role.team("writers"), Role.team("admin")]), // Only writers and admins can edit this document
We now only allow one role per permission

```suggestion
        Permission.update(Role.team("writers")), // Writers can update this document
        Permissions.update(Role.team("admin")), // Admins can update this document
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +        Permission.delete([Role.user("5c1f88b42259e"), Role.team("admin")]) // Only user 5c1f88b42259e and admins can delete this document
```suggestion
       Permission.delete(Role.user("5c1f88b42259e")) // User 5c1f88b42259e can delete this document
       Permission.delete(Role.team("admin")) // Admins can delete this document
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/permissions.phtml
> +        Permission.edit(Role.team("5c1f88b87435e", "owner")), // Only users of team 5c1f88b87435e with the role owner can edit the document
```suggestion
        Permission.update(Role.team("5c1f88b87435e", "owner")), // Only users of team 5c1f88b87435e with the role owner can update the document
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/realtime.phtml
> +    <p>All subscriptions are secured by the <a href="/docs/permissions">permissions system</a> offered by Appwrite, meaning a user will only receive updates to resources to which they has permission
```suggestion
    <p>All subscriptions are secured by the <a href="/docs/permissions">permissions system</a> offered by Appwrite, meaning a user will only receive updates to resources they have permission to access.</p>
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/service.phtml
> +                                <p>To access this route, init your SDK with your project unique ID and <a href="/docs/keys">API Key</a> secret token. Make sure your API Key is granted with access to
```suggestion
                                <p>To access this route, init your SDK with your project unique ID and an <a href="/docs/keys">API Key</a>. Make sure your API Key is created with the <u>"<?php echo $scope; ?>"</u> scope. You can also authenticate using a valid <a href="/docs/client/account#accountCreateJWT">JWT</a> and perform actions on behalf of your user.</p>
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/service.phtml
> +                                <p>To access this route, init your SDK with your project unique ID and <a href="/docs/keys">API Key</a> secret token. Make sure your API Key is granted with access to
```suggestion
                                <p>To access this route, init your SDK with your project unique ID and an <a href="/docs/keys">API Key</a>. Make sure your API Key is create with the <u>"<?php echo $scope; ?>"</u> scope.</p>
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/storage.phtml
> +<p>Storage Service allows you to configure permissions at both the bucket level and the file level. When a user has the appropriate type of <a href="/docs/permissions/">access permissions</a> granted
```suggestion
<p>The Storage Service allows you to configure permissions at both the bucket level and the file level. When a user has the appropriate type of <a href="/docs/permissions/">access permissions</a> granted at **either** the bucket or the file level, they will be able to access the file. If the permission field is left empty, no one can access the file.</p>
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/storage.phtml
> +    <p>For security purposes, an active Account session is required to create resources. So, even if wildcard write permissions are set, only logged-in users can create files in a bucket. If you requ
> For security purposes, an active Account session is required to create resources.

This is no longer true

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/storage.phtml
>  <p>Unlike collections, storage buckets have more configuration options regarding the type and size of the files in the bucket, encryption, and anti-virus scanning. If you look at the bucket settings
No need for a comparison to collections here

```suggestion
<p>Storage buckets have many configuration options, including the type and maximum size of files in the bucket, whether encryption or anti-virus is enabled,  and the compression algorithm to use. If you look at the bucket settings or the REST API example above, you can find these configurations. Let's look at what those are:</p>
```

2022-09-03 01:37 UTC, abnegate commented on app/views/docs/storage.phtml
>  <p>Unlike collections, storage buckets have more configuration options regarding the type and size of the files in the bucket, encryption, and anti-virus scanning. If you look at the bucket settings
Looks like we might need to add some updates below here detailing the new `compression` attribute on buckets

2022-09-14 09:56 UTC, christyjacob4 commented on app/views/docs/databases.phtml
> +    <p>For security purposes, an active Account session is required to create resources. So, even if wildcard write permissions are set, only logged-in users can create documents in a collection. Cre
addressed

2022-09-14 10:37 UTC, merged