File Input Documentation
appwrite/docs pull request #339
Opened 2023-02-21 22:49 UTC by gewenyu99

## What does this PR do?

We have a gap in our storage docs. After introducing the `InputFile` class in many SDKs, we don't document this behavior clearly. This will be added, and the `createFile` endpoints will have updated descriptions that point here.

@Meldiron @abnegate @lohanidamodar Please help me fill in the `InputFile` implementations you worked on.

If no `InputFile` class is available, you can document some examples like this.
<img width="855" alt="Screenshot 2023-02-21 at 5 46 18 PM" src="https://user-images.githubusercontent.com/29069505/220476117-a0af33d5-7201-4420-9f7e-9dc89a4b89d0.png">

If `InputFile` is available with multiple ways to use, you can use a table:
<img width="855" alt="Screenshot 2023-02-21 at 5 49 21 PM" src="https://user-images.githubusercontent.com/29069505/220476572-de994c65-b222-40ab-affa-ab7c0eb75f1e.png">

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2023-02-22 00:37 UTC, abnegate commented
@gewenyu99 

**Apple/Swift**
`InputFile.fromPath(_ path: String)`: Used to upload files from a provided path.
`InputFile.fromData(_ data: Data, filename: String, mimeType: String)`: Used to upload files from a [Data](https://developer.apple.com/documentation/foundation/data) object.
`InputFile.fromBuffer(_ buffer: ByteBuffer, filename: String, mimeType: String)`: Used to upload files from a [NIO ByteBuffer](https://swiftinit.org/reference/swift-nio/niocore/bytebuffer) object.

**Kotlin/Android:**
`InputFile.fromPath(path: String)`: Used to upload files from a provided path.
`InputFile.fromFile(file: File)`: Used to upload files from a provided [File](https://docs.oracle.com/javase/8/docs/api/java/io/File.html) object.
`InputFile.fromBytes(bytes: ByteArray, filename: String, mimeType: String)`: Used to upload files from a [ByteArray](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-byte-array/) object.

**Ruby:**
`Input.from_path(path)`: Used to upload files from a provided path.
`Input.from_string(string)`: Used to upload files from string content.
`Input.from_bytes(bytes)`: Used to upload files from an array of bytes.

**Python:**
`Input.from_path(path)`: Used to upload files from a provided path.
`Input.from_bytes(bytes)`: Used to upload files from an array of bytes.

2023-02-23 23:19 UTC, gewenyu99 commented
@Meldiron @lohanidamodar Can you provide some information about the InputFile classes you implemented ? 😃

2023-02-24 09:54 UTC, Meldiron commented
Rest - no changes
GraphQL - no changes
CLI - no changes
Web: No changes (we probably should implement)
Dart: constructor with `path` or `bytes` ( https://github.com/appwrite/sdk-for-dart/blob/master/lib/src/input_file.dart#L11 )
Flutter: Same as Dart ( https://github.com/appwrite/sdk-for-flutter/blob/master/lib/src/input_file.dart#L11 )
Deno: `fromPath() fromBuffer() fromPlainText()` ( https://github.com/appwrite/sdk-for-deno/blob/master/src/inputFile.ts#L15-L33 )
Node: `fromPath(), fromBuffer(), fromBlob(), fromStream(), fromPlainText()` ( https://github.com/appwrite/sdk-for-node/blob/master/lib/inputFile.js#L10-L38 )
PHP:  `withPath() and withData()` ( https://github.com/appwrite/sdk-for-php/blob/master/src/Appwrite/InputFile.php#L32-L50 )

2023-02-26 05:29 UTC, lohanidamodar commented
@gewenyu99 @Meldiron @Meldiron I'm thinking of deprecating the constructors that accepts either path or bytes and instead introduce `InputFile.fromBytes` and `InputFile.fromPath` just like that of swift and android?

2023-03-09 01:17 UTC, lohanidamodar commented on app/views/docs/storage.phtml
> +            <td><code>InputFile.fromPath(path: [PATH], filename: [NAME], contentType: [MIME TYPE])</code></td>
For path, filename and content type are optional

2023-03-09 01:18 UTC, lohanidamodar commented on app/views/docs/storage.phtml
> +            <td><code>InputFile.fromBytes(filename: [NAME], contentType: [MIME TYPE], bytes: [BYTE LIST])</code></td>
for bytes filename and bytes are required (can we do bytes first, filename second, and content type last ) mention content-type to be optional

2023-03-09 01:18 UTC, lohanidamodar requested changes
Left couple comments for Flutter.

2023-03-10 06:56 UTC, lohanidamodar approved these changes
Flutter looks good.

2023-03-16 02:33 UTC, abnegate approved these changes

2023-03-16 08:15 UTC, Meldiron commented on app/views/docs/storage.phtml
> +        For example, for the input tag <code><?php echo htmlentities('<input type="file" id="uploader" multiple />'); ?></code>, you would call create file like this:
```suggestion
        For example, for the input tag <code><?php echo htmlentities('<input type="file" id="uploader" />'); ?></code>, you would call create file like this:
```

I would remove `multiple`. That way browser only let's you pick one, so doing `[0]` later is cool.

If they want to upload multiple files, they would need for loop.

2023-03-21 07:54 UTC, Meldiron approved these changes

2023-04-11 09:37 UTC, merged