Amend documented behavior for cascade on delete.
appwrite/docs pull request #364
Opened 2023-04-27 17:03 UTC by gewenyu99

## What does this PR do?

There's an exception for cascade on delete for many-to-one, where deleting the single child cascades and not the other way around.

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2023-04-27 17:07 UTC, stnguyen90 requested changes

2023-04-27 17:07 UTC, stnguyen90 commented on app/views/docs/databases-relationships.phtml
> +<p>If the on-delete behavior is <b>cascade</b>, deleting the parent documents also deletes <b>related child documents</b>, except for many-to-one relationships. In many-to-one relationships, there ar
It would be good to explicitly mention one-to-many as well.

2023-04-27 17:11 UTC, stnguyen90 approved these changes

2023-04-28 00:29 UTC, abnegate approved these changes

2023-04-28 00:30 UTC, merged