Updated OAuth docs regarding selection of application type
appwrite/docs pull request #369
Opened 2023-05-19 15:04 UTC by Rohit-RA-2020

## What does this PR do?

Updates the doc regarding selection of application type in OAuth providers

## Test Plan

Doc updates

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-05-19 15:09 UTC, Rohit-RA-2020 commented
Hey @gewenyu99, you can review this

2023-05-19 18:08 UTC, gewenyu99 requested changes

2023-05-19 18:08 UTC, gewenyu99 commented on app/views/docs/authentication.phtml
> +    <p>While you setup OAuth2 providers, you need to enter App ID and App Secret in your Appwrite console. You need to choose a web application in your respective 3rd party OAuth2 provider (Ex: Googl
```suggestion
    <p>You should select <b>web application</b> as the application type in your OAuth2 provider, even if you're building a mobile or flutter application. The OAuth2 provider will communicate with Appwrite directly, which is a web application.</p>
```

2023-05-23 20:30 UTC, gewenyu99 approved these changes

2023-05-23 20:30 UTC, gewenyu99 approved these changes

2023-05-29 20:57 UTC, gewenyu99 approved these changes

2023-05-29 20:57 UTC, gewenyu99 commented on app/views/docs/authentication.phtml
> +    <h3>Note</h3>
On second thought, can you suggest some better titles for this than "Note"? We don't use generic titles like this.

2023-05-29 20:57 UTC, gewenyu99 requested changes
See previous comment

2023-08-01 17:12 UTC, closed without merging